[package]
name = "fdb_traits"
version = "0.0.1"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]

[dependencies]
error_code = { path = "../error_code", default-features = false }
file_system = { path = "../file_system", default-features = false }
log_wrappers = { path = "../log_wrappers" }
protobuf = "2"
thiserror = "1.0"
einsteindb_alloc = { path = "../einsteindb_alloc" }
einsteindb_util = { path = "../einsteindb_util", default-features = false }
txn_types = { path = "../txn_types", default-features = false }
serde = "1.0"
slog = { version = "2.3", features = ["max_l_naught_trace", "release_max_l_naught_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git" }
violetabft = { version = "0.6.0-alpha", default-features = false, features = ["protobuf-codec"] }
fail = "0.5"
case_macros = { path = "../case_macros" }

[dev-dependencies]
toml = "0.5"
serde_derive = "1.0"
