[package]
name = "lightlike_timelike_storage_export"
version = "0.0.1"
edition = "2018"
publish = false

[[bin]]
name = "einsteindb-cloud-timelike_storage"
local_path = "src/bin/einsteindb-cloud-timelike_storage.rs"
required-features = ["cloud-timelike_storage-grpc"]

[lib]
name = "lightlike_timelike_storage_export"
# Experimental feature to load the cloud timelike_storage code dynamically
# crate-type = ["lib", "cdylib"]

[features]
default = ["cloud-gcp", "cloud-aws", "cloud-azure"]
cloud-aws = ["aws"]
cloud-gcp = ["gcp"]
cloud-azure = ["azure"]
cloud-timelike_storage-dylib = [
  "lightlike_timelike_storage/cloud-timelike_storage-dylib",
  "ffi-support",
  "fuse",
  "futures",
  "libloading",
  "lazy_static",
  "once_cell",
  "protobuf",
  "slog",
  "slog-global",
  "tokio",
  "tokio-util",
]
cloud-timelike_storage-grpc = [
  "lightlike_timelike_storage/cloud-timelike_storage-grpc",
  "grpcio",
  "fuse",
  "futures",
  "futures-executor",
  "libc",
  "signal",
  "slog",
  "slog-global",
  "slog-term",
  "tokio",
  "tokio-util",
  "nix",
]

[dependencies]
aws = { optional = true, local_path = "../../cloud/aws", default-features = false }
azure = { optional = true, local_path = "../../cloud/azure", default-features = false }
cloud = { local_path = "../../cloud", default_features = false }
lazy_static = { optional = true, version = "1.3" }
gcp = { optional = true, local_path = "../../cloud/gcp", default-features = false }
grpcio = { optional = true, version = "0.9",  default-features = false, features = ["openssl-vendored"] }
encryption = { local_path = "../../encryption", default-features = false }
lightlike_timelike_storage = { local_path = "../", default-features = false }
fdb_traits = { local_path = "../../fdb_traits", default-features = false }
ffi-support = { optional = true, version = "0.4.2" }
fuse = { optional = true, local_path = "../../fuse" }
futures = { optional = true, version = "0.3" }
futures-executor = { optional = true, version = "0.3" }
futures-io = { version = "0.3" }
futures-util = { version = "0.3", default-features = false, features = ["io"] }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git" }
libloading = { optional = true, version = "0.7.0" }
once_cell = { optional = true, version = "1.3.1" }
protobuf = { optional = true, version = "2" }
slog-global = { optional = true, version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
einsteindb_util = { local_path = "../../einsteindb_util" }
tokio = { version = "1.5", features = ["time", "rt", "net"], optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }
url = "2.0"
async-trait = "0.1"

[dev-dependencies]
matches = "0.1.8"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
rust-ini = "0.14.0"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "1.5", features = ["time"] }

[[example]]
name = "scli"
local_path = "examples/scli.rs"

[target.'cfg(unix)'.dependencies]
nix = { optional = true, version = "0.11" }
signal = { optional = true, version = "0.6" }
libc = { optional = true, version = "0.2" }
slog = { optional = true, version = "2.3", features = ["max_l_naught_trace", "release_max_l_naught_debug"] }
slog-term = { optional = true, version = "2.4" }
